### ISSUE TITLE
Support for ServiceStack.Text 4

### ISSUE THREAD

**Issue by circuitrider** [nerdfury/Slack.Webhooks#12]
forked it here for my needs for now
https://github.com/circuitrider/Slack.Webhooks

Not sure how to handle this version cutover cleanly with NuGet considerations, which I would rather use than my own local repo.

**Comment by nerdfury** [comment]
Hey, I just pushed a new version to NuGet that *should* support ServiceStack v3 and v4. By default it installs the non-commercial (v3) version but can be upgraded from the package manager. RestSharp is also left at an older version to maintain .NET 3.5 support.

Give it a go and see how it goes, let me know if you have any issues?

**Comment by nerdfury** [comment]
Assuming no news is good news =)

**Comment by circuitrider** [comment]
Sorry for nonresponse. Was super busy and forgot about this. Still running my branch, will go back to yours in my next sprint. Thanks again for your work on this project. Much appreciated.
