### ISSUE TITLE
add link_names property to SlackMessage class

### ISSUE THREAD

**Issue by rzaitov** [nerdfury/Slack.Webhooks#13]
By default Slack doesn't linkify user names, but we can enable this behaviour providing link_names=1 inside payload.

Please have a look at the [docs](https://api.slack.com/docs/formatting) (**Parsing modes** section)
Interesting discussion about this issue on [google groups](https://groups.google.com/forum/#!topic/slack-api/HBmj2XaG_g0)

**Comment by roisin-jin** [comment]
hello rzaitov,

I've tried to use this setting several times in incoming webhook, however it's not working
Can you let me know where's my mistake?
payload={"text" : "apitest #slack-watchlist","link_names": 1 }

Many thanks

**Comment by rzaitov** [comment]
Hello @roisin-jin
> I've tried to use this setting several times in incoming webhook, however it's not working

It is not clear for me what exactly doesn't work. Do you mean message delivery itself or just linkify channel names (usernames)?

I just tested the following with curl and it works perfectly:
```curl -X POST --data-urlencode 'payload={"text": "This is a test message to #general from @some-nick from *monkey-bot*.", "channel": "#general", "username": "monkey-bot", "icon_emoji": ":monkey_face:", "link_names":1}' "https://hooks.slack.com/services/XXXX"```

**Comment by roisin-jin** [comment]
Hi rzaitov, 

I mean the linkify channel name part. The message sent out successfully however the channel name is not linked, but just like the normal text. This features seems working fine with chat.postMessage and slack's own incoming-webhook, but not for the application i setup on slack

Thanks

**Comment by nerdfury** [comment]
Added LinkNames and Parse in v0.1.6 =)
