### ISSUE TITLE
The nuget package assembly is not strong named

### ISSUE THREAD

**Issue by nadzzz** [nerdfury/Slack.Webhooks#22]
Can the build assembly have a strong name? It will make it able to include it in strong named projects.

**Comment by nerdfury** [comment]
Hey, sorry this has been open so long, I'll take a look at what's involved in packaging up a signed version (or separate nuget package)

**Comment by mxmissile** [comment]
@nadzzz can do it yourself with https://github.com/dsplaisted/strongnamer

**Comment by nerdfury** [comment]
@mxmissile that is a great solution, thanks for sharing!
