### ISSUE TITLE
PostAsync not working

### ISSUE THREAD

**Issue by Javietto** [nerdfury/Slack.Webhooks#24]
Hello,

I get the message code "missing_text_or_fallback_or_attachments" as internal server error when using PostAsync. The same call with the same parameters works fine if I use the non async method.

Can you help? My request contains attachments, if it helps.

Thank you

**Comment by nerdfury** [comment]
Hey, Apologies, there has been a PR kicking around that addresses this problem for a while, now merged and will push an updated package soon.
