### ISSUE TITLE
Nuget Install Issues

### ISSUE THREAD

**Issue by thnk2wn** [nerdfury/Slack.Webhooks#25]
Created a new ASP.net core web app (.net framework), targeting .net framework 4.6.2 and slack.webhooks 0.1.6.

Error in install:

> error: Package ServiceStack.Text 3.9.71 is not compatible with net462 (.NETFramework,Version=v4.6.2). Package ServiceStack.Text 3.9.71 supports:
> error:   - net35 (.NETFramework,Version=v3.5)
> error:   - sl4 (Silverlight,Version=v4.0)
> error:   - sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
> error:   - sl5 (Silverlight,Version=v5.0)
> error: One or more packages are incompatible with .NETFramework,Version=v4.6.2.

Also the 0.1.6 version fails on install in a class library targeting 4.6.2 - doesn't add a reference to slack web hooks assembly. Don't see the above error though.

**Comment by thnk2wn** [comment]
Reverting to 0.1.5 fixes problem 2 above with .net standard and it not adding the reference to slack.webhooks. Doesn't help the asp.net core issue though.

**Comment by nerdfury** [comment]
Can you install RestSharp in a dotnet core project? If so, I may have a solution on another branch removing the ServiceStack.Text dependency.

**Comment by piersmacdonald** [comment]
Doesn't look like it. But there is a RestSharp.Core (https://www.nuget.org/packages/RestSharp.NetCore/)

IMO, I'd just use HttpClient in System.Http

Package RestSharp 104.4.0 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package RestSharp 104.4.0 supports:
  - net35 (.NETFramework,Version=v3.5)
  - net35-client (.NETFramework,Version=v3.5,Profile=Client)
  - net40 (.NETFramework,Version=v4.0)
  - net40-client (.NETFramework,Version=v4.0,Profile=Client)
  - sl4 (Silverlight,Version=v4.0)
  - sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
Package ServiceStack.Text 3.9.71 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package ServiceStack.Text 3.9.71 supports:
  - net35 (.NETFramework,Version=v3.5)
  - sl4 (Silverlight,Version=v4.0)
  - sl4-wp71 (Silverlight,Version=v4.0,Profile=WindowsPhone71)
  - sl5 (Silverlight,Version=v5.0)

**Comment by nerdfury** [comment]
I've published 1.0.0-rc1 which removes RestSharp completely and should support netcore if you'd like to give it a whirl?
