### ISSUE TITLE
Add an ISlackClient interface for easy mocking

### ISSUE THREAD

**Issue by richardthombs** [nerdfury/Slack.Webhooks#26]
I'd like to be able to use FakeItEasy to mock a SlackClient for tests and because FakeItEasy can only create fakes for interfaces, I really need an ISlackClient interface.

If I do the PR, would you be OK with that?

Cheers,

R.

**Comment by nerdfury** [comment]
Sure, put something together and we'll go from there.

**Comment by clintdavis77** [comment]
I'd love to see @richardthombs PR merged in. Let me know if I can help in any way.

**Comment by nerdfury** [comment]
Pushed version 0.1.8 with this change, many thanks 👍
