### ISSUE TITLE
Footers and Time Stamps

### ISSUE THREAD

**Issue by RIKIKU** [nerdfury/Slack.Webhooks#30]
It looks like the WebHooks API now supports TimeStamps, footer and footer_Icon in the message attachment.
Support for this should probably be added at some stage.

**Comment by winzig** [comment]
This fix seems to have been reverted in https://github.com/nerdfury/Slack.Webhooks/commit/4cf716cf96cdeae674e165e1363a8b7bd456dfae#diff-a4ceebd58deebfcd981cbf845072191e
