### ISSUE TITLE
Message Buttons

### ISSUE THREAD

**Issue by mqueirozcorreia** [nerdfury/Slack.Webhooks#33]
Are you planning to add support to message buttons?
https://api.slack.com/docs/message-buttons

It needs to set callback_id in the attachmens and add actions field, to enable options

**Comment by nerdfury** [comment]
I actually started this a little while back but never finished, will look and see if I can get something together over the weekend!

**Comment by mqueirozcorreia** [comment]
I'll try to code that and contribute. Maybe not this weekend.  :smile:

**Comment by nerdfury** [comment]
I'd already done a chunk of it, have pushed the branch which i think is complete, please feel free to take a look and test it out maybe? i've run through a bunch of scenarios with buttons/menus etc which appear to work as expected.

https://github.com/nerdfury/Slack.Webhooks/tree/interactive-buttons

let me know what you think.

**Comment by mqueirozcorreia** [comment]
It's is working! I just got into a problem(already solved now) and I would like to know if you want some help to improve.
Following the docs (https://api.slack.com/docs/interactive-message-field-guide) the action.type should be "button" or "select". When I mistyped "Button", no button was appearing.
Your idea to have it's type as string is to make it more flexible? Or do you think that a enum there would be more helpful?

**Comment by nerdfury** [comment]
So the problem as I saw it with an enum was that when serialised it uses the enum value rather the enum text. What I actually did (which I agree isn't immediately obvious) was add SlackAction.Type with some constructive values for Button and Select (should actually be more like the emojii.cs)

**Comment by mqueirozcorreia** [comment]
No need to answer that. There is a static Type.Button.

**Comment by mqueirozcorreia** [comment]
Why don't you call the Action class as SlackAction, the same way you did with Message (Which is named SlackMessage)? If you do so, you don't have namespace conflict with System.Action and Slack.Webhooks.SlackAction.Action.

That next is totally preference. Why are you naming the namespace as "Slack.Webhooks.SlackAction" instead of "Slack.Webhooks.Action"

**Comment by nerdfury** [comment]
Yeah completely fair points, I wasn't 100% on my decision to change it, happy for you to refactor a bit  and maybe we can come up with something better ☺️

**Comment by mqueirozcorreia** [comment]
Pull request made refactoring Action class and namespace.
I will think about other classes too (Like type)

**Comment by nerdfury** [comment]
I'm messing with this still a little, mostly because I really want to move towards your suggestion of having the Type, Style etc as Enums. For this i'm going to move ahead with my migration from SeviceStack.Text to JSON.net which allows me to do this quite easily (and rename some of the properties that trigger my ocd ;) ) will push an update soon - probably later today.

**Comment by nerdfury** [comment]
Hey, can you let me know your thoughts on the current version of interactive-buttons and then start thinking about merging them in a pushing an updated nuget package. thanks :)

**Comment by mqueirozcorreia** [comment]
Nice, I think we should rename the Type class to something as SlackActionType, or anything else. Otherwise we have a name conflict between it and System.Type. I can do that if you like.

I don't think that is needed to change json package. I'm more comfortable with newtonsoft.json, but ServiceStack.Text solved the problem.

I'm actions of type button and it works fine!

Please let me know if you need any help.

**Comment by nerdfury** [comment]
So I think the current enum is named SlackActionType anyways?

There have been requests (on grounds on servicestack.text not being free)
to move to json.net (even though the version it ships with is
pre-commercial version) which I have dismissed, but I've been looking at
making a dotnet core version and json.net has a compatible version! And the
ability to decorate properties with an attribute to change the output is a
but upside!

**Comment by mqueirozcorreia** [comment]
The point is to not use Type as name, if you have a better name than SlackActionType I think it will be ok too.

Using the [EnumMemberAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.serialization.enummemberattribute.aspx) sounds better. Googling [I found this package with claims to support to ServiceService.Text](https://github.com/Chatham/ServiceStack.Text.EnumMemberSerializer/blob/master/src/ServiceStack.Text.EnumMemberSerializer/PrettyEnumExtensions.cs). But [Json.net supports by default](https://stackoverflow.com/a/24995368/3424212). I have never used ServiceStack.Text so I can't blame it for anything yet, but I really like Json.net.

If you change the class name, I think you can change json serializer later (in order to make you more comfortable as you have not picked Json.net as first choice). Or at leat, try using the new name before making a new nuget version.

**Comment by nerdfury** [comment]
like this perhaps?

```csharp
[JsonProperty(PropertyName = "type")]
public SlackActionType ActionType
{
    get { return _type; }
    set { _type = value; }
}
```

**Comment by mqueirozcorreia** [comment]
This should be just fine:
`public SlackActionType Type
{
    get { return _type; }
    set { _type = value; }
}`

The problem is when you need to use like below
`Using System;
Using Slack.Webhooks.Action;
...
Message.Type = Type.Button; // it conflicts with System.Time
Message.Type = SlackActionType.Button; // no conflicts, works great!
`

What do you think?

**Comment by nerdfury** [comment]
think that sounds perfect since that is what is already done :D

https://github.com/nerdfury/Slack.Webhooks/blob/interactive-buttons/src/Slack.Webhooks/Enums.cs#L43

https://github.com/nerdfury/Slack.Webhooks/blob/interactive-buttons/src/Slack.Webhooks/SlackAction.cs#L27

**Comment by mqueirozcorreia** [comment]
I didn't have time yet to update my branch and test. It may take some more days ok? But I'll give you feedback.

**Comment by mqueirozcorreia** [comment]
I have just updated my source and it is working perfectly!

**Comment by mqueirozcorreia** [comment]
If you want, you can close this issue now!
Let me know if you need any other help.
