### ISSUE TITLE
Reflection Error on Emoji.cs 

### ISSUE THREAD

**Issue by danatcofo** [nerdfury/Slack.Webhooks#40]
Hit a reflection error on duplicate definitions of Icecream/IceCream.  This needs to be spelled differently in some way.  Recommend using Icecream/Ice_Cream to follow the `EnumMember` spellings for transparency.

System.ArgumentException : Duplicate item already exists for 'Icecream' at Newtonsoft.Json.Utilities.BidirectionalDictionary`2.Set(TFirst first, TSecond second)

**Comment by nerdfury** [comment]
Thanks for reporting this, hopefully this should be resolved in the 1.0 release, let me know if there are still issues.
