### ISSUE TITLE
Missing release versions?

### ISSUE THREAD

**Issue by winzig** [nerdfury/Slack.Webhooks#50]
The releases page latest version numbers are 0.1.8, 0.1.7, etc. But the [Nuget page](https://www.nuget.org/packages/Slack.Webhooks/) has release numbers available of 1.0.0 and higher. Is it just that that some commits have not been tagged with those release numbers yet?

**Comment by nerdfury** [comment]
Hey man, looks like i just forgot to push them. have done so now.
