### ISSUE TITLE
Suggestion - Move SerializePayload into SlackMessage

### ISSUE THREAD

**Issue by pmacca** [nerdfury/Slack.Webhooks#54]
Hi - thanks for sharing this project, it's been very useful.

I've been using the project to send messages to Slack and it's working very well 👍.

I am now trying to respond to message buttons and come across a couple of problems:

1. A couple of fields for message replies are missing. See my PR here: https://github.com/nerdfury/Slack.Webhooks/pull/53

2. To do a reply, I need to reply to a request, rather than sending a new message. In order to do so, I need to serialize the `SlackMessage`. Serializing has a tiny bit of configuration relating to snake casing (https://github.com/nerdfury/Slack.Webhooks/blob/master/src/Slack.Webhooks/SlackClient.cs#L60). This method is private in SlackClient, and I'd prefer not to copy it into my own application in case it changes at some point.

Example:
![image](https://user-images.githubusercontent.com/3015297/39682128-7fdd8c8e-51f1-11e8-81b2-adbde849320d.png)

SUGGESTION: How about making `string SerializePayload(SlackMessage slackMessage)` an instance method on `SlackMessage`? Alternatively just make that static method public?

Cheers

**Comment by nerdfury** [comment]
v1.0.5 should be available now with this in it.
