### ISSUE TITLE
Post doesn't convert \n in text to multiline

### ISSUE THREAD

**Issue by TonyGravagno** [nerdfury/Slack.Webhooks#8]
I'm not sure if this is an issue in the Slack API or in this client. Has anyone been able to get multi-line text?  Example text = "foo\nbar". That exact text displays in Slack. I've tried setting mrkdwn to true and false as well as trying a number of permutations like \\n, &#10;, %5c, %255c, \r\n, \\\\n, and other insanity like surrounding the text in spaces. Thanks.

**Comment by nerdfury** [comment]
Hi Tony, apologies, i've been away, i'll take a look

**Comment by nerdfury** [comment]
hmmmm... it seems to work using the following:

```csharp
var message = new SlackMessage
{
    Channel = "#apitest",
    Text = "This is a line of text.\n\nAnd this is another one.",
    IconEmoji = Emoji.Alien,
    Username = "nerdbot"
};
```

![image](https://cloud.githubusercontent.com/assets/944655/7409872/e169a5f4-ef21-11e4-8923-96aa9e8bb07a.png)

are you still having this issue?

**Comment by TonyGravagno** [comment]
Thanks for the response Benn. This is an app issue. The library is fine. Sorry for the bother. But your confirmation helped me to follow the debugging a little more closely. I'll leave this here for posterity and maybe this will translate to an enhancement.

I'm getting the text from outside the code, whether command-line or another program. The text includes the two characters "\n". So the slash gets escaped resulting in "\\n". It's the equivalent of using @"foo\nbar". To fix this the value I'm now assigning to SlackMessage.Text is Regex.Unescape(text). So the two character \n gets converted to a single ASCII CR character, which is what's expected by the Slack API.

As to an enhancement, what do you think about this?

```C#
// in SlackMessage
using System.Text.RegularExpressions;
...
public string UnescapedText // set Text _or_ UnescapedText, not both
{
    get
    {
        return Regex.Escape(Text); // Result could be undesirable
    }
    set
    {
        Text = Regex.Unescape(value);
    }
}
```

**Comment by nerdfury** [comment]
Hey Tony, sorry again for taking so long to get around to this. have pushed a couple of options for this problem provided (big assumption on my part) that once you've made the SlackMessage object that you no longer care how the incoming message was escaped.

To summarize, the 2 options look like this:

Option 1.
```csharp
var message = new SlackMessage(TextType.Escaped);
message.Text = @"This is a\nMulti-line message";
Console.WriteLine(message.Text); // "This is  a\\nMulti-line message"
```

Option 2
```csharp
var message = new SlackMessage();
message.EscapedText = @"This is a\nMulti-line message"; // setter only
Console.WriteLine(message.Text); // "This is a\\nMulti-line message"
```

Looking at it now, i think i prefer Option 1 as it feels cleaner, but let me know what you think.

**Comment by TonyGravagno** [comment]
I see what you've done. Thank you very much for translating this into an enhancement. As to option 1 or option 2, it's simply good to have options to suit personal preferences/needs. It will take several days for me to pull the latest build and take it for a run but I promise that I will do so, and will return here to comment.

**Comment by nerdfury** [comment]
Thanks Tony.

**Comment by jfrumar** [comment]
We are integrated with GitHub via webhooks, and only ever get the first line of the commit message. Is there a way to configure GitHub/Slack to play better together?
