### ISSUE TITLE
Markdown in attachments

### ISSUE THREAD

**Issue by sjk07** [nerdfury/Slack.Webhooks#9]
In the slack api docs they state that attachments by default have markdown turned off.
The only way to enable them is to pass the mrkdwn_in field and pass an array of the items that should have markdown enabled.

https://api.slack.com/docs/formatting

```json
"attachments": [
        {
            "title": "Title",
            "pretext": "Pretext _supports_ mrkdwn",
            "text": "Testing *right now!*",

            "mrkdwn_in": ["text", "pretext"]
        }
    ]
``` 

A basic solution would be to add the `Mrkdwn_in` variable to `SlackAttachment` class
```c#
public List<string> Mrkdwn_in {get;set;}
```

To make this better have accessible variables that return the possible fields that markdown can be enabled on `pretext`, `text`, `fields`

**Comment by samblackmore** [comment]
Thank you! I really wanted markdown in my attachments
